DROP TABLE IF EXISTS boxes CASCADE;
CREATE TABLE boxes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  active_status BOOLEAN DEFAULT FALSE
);
