INSERT INTO farms (user_id, name, logo_url, email, password, description, active_status, street_address, city, postal_code, phone, is_family_owned, is_organic, registered_at)
VALUES
(1, 'Silver Lane Farm', 'https://dypdvfcjkqkg2.cloudfront.net/large/3912098-4202.png', 'tay@harvest.com', '1234', 'Our small farm is producing fresh, home-grown vegetables and fruit. Apples, rhubarb, tomatoes, broccoli, carrots, squash, pumpkins, beans, beets, vegetable baskets toorder, mint, basil, sweet pea flowers and free range eggs. Local hay sometimes available.', true, '1595 John Road', 'North Saanich', 'V8L-5S8', '250-655-9175', true, true, '2022-09-25T07:00:00.000Z'),
(1, 'Farm Fresh', 'https://www.clipartmax.com/png/middle/104-1041781_organic-food-farm-logo-agriculture-free-vector-farm-logos.png', 'tay2@harvest.com', '1234', 'Family farm operated since 1960. Local produce picked daily in our greenhouses. TOMATOES: Beefsteak, On the Vine, Roma, Heirloom, Red and Yellow cherry tomatoes, Green tomatoe, Canning tomatoes. Crispy long English and Mini cucumbers. Sweet Red and Yellow Peppers, Hot Cayenne and Jalapeno Peppers, Eggplants, Beans, Sweet basil, Scarlet runner beans, Fuzzy melon, Winter melon, Bitter melon and More seasonal vegetables. Find us at farmers markets as well at our farm. Non GMO. No pesticides used. Good bugs are used for pest control.', true, '3968 Glanford Avenue', 'Victoria', 'V8Z-3Z4', '250-479-4738', true, false, '2022-09-25T07:00:00.000Z'),
(2, 'Green Farm', 'https://img.favpng.com/9/21/5/organic-food-logo-organic-farming-agriculture-png-favpng-Lv398LpfpaPEHCWwWTx89itHv.jpg', 'ryan@harvest.com', '1234', 'Longview Farms is the largest Certified Organic farm on Vancouver Island and our produce, flowers and bulbs can be found in a number of local retail stores throughout Vancouver Island and the mainland. We grow a wide variety of Certified Organic vegetable crops and strawberries as well as conventional fresh-cut daffodils, daffodil bulbs, pumpkins, and hay.

Longview Farms is highly committed to a healthy local food system.  Our goal is to have a positive impact on local food security issues by increasing production and innovating to meet the ever-changing needs of our community.', true, '8277 Central Saanich Road', 'Saanichton', 'V8M-1T7', '250-652-3276', false, true, '2022-09-25T07:00:00.000Z'),
(2, 'Flow Organics', 'https://www.48hourslogo.com/oss/attachments/2022/08/08/16320353352/120176_18522_64ac0cee-af65-49e5-a055-7de5de1b9d9c.jpg', 'ryan2@harvest.com', '1234', 'We are committed to farming organically and sustainably for a healthier, happier community. Our food is safe and nutritious; grown without harmful synthetic pesticides or synthetic fertilisers. We sustain the soil using techniques such as composting, cover cropping and crop rotation. Pest control is achieved through preventative measures such as screening and covering crops against pests, as well as introducing beneficial insects and micro-organisms that either attack pests or colonize plant and soil to keep pests out.

We are certified organic by Islands Organic Producers Association (IOPA), member number 1960.', true, '2200 Bear Hill Road', 'Victoria', 'V8M-1X7', '250-652-9722', false, true, '2022-09-25T07:00:00.000Z'),
(3, 'Underfoot Farms', 'https://www.48hourslogo.com/oss/works/2021/04/15/0411490552/108147_50227_99114590-5077-4803-a301-5cf16fd4b6f8.jpg', 'anouk@harvest.com', '1234', '
Saanich Organics is a community of farmers from small, certified organic farms who work together to supply fresh local produce and top-quality organic seeds to Greater Victoria BC. Heather Stretch of Northbrook Farm, Robin Tunnicliffe of Sea Bluff Farm, and Rachel Fisher of Three Oaks Farm have co-owned the business since 2002, and we work with several other farmers in and around greater Victoria.

Saanich Organics has been featured in numerous publications, including the National Post, Times Colonist, West Jets Up! Magazine, EAT Magazine, Douglas Magazine, BC Business, Boulevard Magazine, The Jewish Independent, and The Province. The business has also been featured in Island on the Edge (a documentary film), as well as on CBC Radio.', true, '1438 Mt Newton Cross Road', 'Saanichton', 'V8M-1S1', '250-652-9035', true, true, '2022-09-25T07:00:00.000Z'),
(3, 'Plentiful Plate Farm', 'https://islandfarmfresh.com/app/uploads/2017/04/4C941857-71BC-4315-960B-F3604F55D201-600x600.jpeg', 'anouk2@harvest.com', '1234', 'A local garden full of fresh vegetables, herbs and fruit for you to enjoy. All grown with only natural methods. We have strawberries, blueberries, fall gold raspberries, red raspberries, blackberries, fruit trees, many vegetable beds and even rental garden beds.', true, '7337 Wallace Drive', 'Saanichton', 'V8M-1S9', '250-514-3335', true, true, '2022-09-25T07:00:00.000Z')
;
